// <auto-generated />
using System;
using CSCMasterAPI.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSCMasterAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("District");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thiruvarur"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nagapattinam"
                        });
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.Entrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CC")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("ChildName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("EID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EIDDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ForeignResident")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GST")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("OperatorAadhaar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PacketSkipped")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingStateDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectReasonDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Uploaded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("MemberId");

                    b.HasIndex("UserId");

                    b.ToTable("Entrollment");
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aadhaar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("LoginAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OnboardDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("UserId");

                    b.ToTable("Member");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aadhaar = "781191892916",
                            Block = "Mannargudi",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "PRAKATHI V",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40288@",
                            Phone = "8428516150",
                            StationId = "40288",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Aadhaar = "414969174894",
                            Block = "KODAVSAL",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "VIVEKA RAJASEKARAN",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40287@",
                            Phone = "9688129202",
                            StationId = "40287",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Aadhaar = "520549764245",
                            Block = "THIRUTHURAIPOONDI\r\n",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "PRAVINSHA ELAVARASAN",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40286@",
                            Phone = "9047595234",
                            StationId = "40286",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Aadhaar = "741948749615",
                            Block = "Mannargudi",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "S SOUNDARAPANDIAN",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "32115@",
                            Phone = "7904784390",
                            StationId = "32115",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Aadhaar = "283319238556",
                            Block = "MUTHUPET\r\n",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "Ganesh anbazhagan",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "52142@",
                            Phone = "9047430909",
                            StationId = "52142",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Aadhaar = "677251519950",
                            Block = "Mannargudi",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "Mohamed Yunus M",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "8228@",
                            Phone = "7200882629",
                            StationId = "8228",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Aadhaar = "401851195105",
                            Block = "NEEDAMANGALAM",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "Ramesh Prabu",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "8224@",
                            Phone = "9245329720",
                            StationId = "8224",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Aadhaar = "516873296730",
                            Block = "NEEDAMANGALAM",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "GANESH R",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "8219@",
                            Phone = "8760849391",
                            StationId = "8219",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Aadhaar = "924108073256",
                            Block = "KODAVASAL",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "SHANMUGAPRIYA P",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "11274@",
                            Phone = "9688925880",
                            StationId = "11274",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Aadhaar = "568932655898",
                            Block = "MANNARGUDI",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "KUMARAN GANAPATHI",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "11272@",
                            Phone = "8870207988",
                            StationId = "11272",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Aadhaar = "828526901867",
                            Block = "Mannargudi",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "Sumathi",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "8222@",
                            Phone = "9042626755",
                            StationId = "8222",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Aadhaar = "984494354407",
                            Block = "MUTHUPET",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "KaniMozhi",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "8219@",
                            Phone = "9003330783",
                            StationId = "8219",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Aadhaar = "700887772985",
                            Block = "Mannargudi",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "ATCHIYA MURUGANANDHAM",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "11179@",
                            Phone = "9751861115",
                            StationId = "11179",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Aadhaar = "885383877726",
                            Block = "Thiruvarur",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "SATHEESH THAMBIYAN",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40362@",
                            Phone = "9543642406",
                            StationId = "40362",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Aadhaar = "283019815916",
                            Block = "THIRUTHURAIPOONDI",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "Govindaraj",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "52012@",
                            Phone = "9751867179",
                            StationId = "52012",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Aadhaar = "712083934553",
                            Block = "NEEDAMANGALAM",
                            District = "Thiruvarur",
                            DistrictId = 1,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "SUBISH SUGUMARAN",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "11176@",
                            Phone = "8270741713",
                            StationId = "11176",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Aadhaar = "256646693269",
                            Block = "NAGOOR",
                            District = "NAGAPATTINAM",
                            DistrictId = 2,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "kaviyarasan",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40361@",
                            Phone = "8072537753",
                            StationId = "40361",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Aadhaar = "544354172245",
                            Block = "KEELAIYUR",
                            District = "NAGAPATTINAM",
                            DistrictId = 2,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "Mathiyarasi Vengadachalam",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "11276@",
                            Phone = "9943092275",
                            StationId = "11276",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            Aadhaar = "672146031183",
                            Block = "KEEVALUR",
                            District = "NAGAPATTINAM",
                            DistrictId = 2,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "saranya",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40360@",
                            Phone = "7339328559",
                            StationId = "40360",
                            Status = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            Aadhaar = "245634561191",
                            Block = "NAGAPATTINAM",
                            District = "NAGAPATTINAM",
                            DistrictId = 2,
                            LoginAllowed = true,
                            Mode = "Online",
                            Name = "yuvashri",
                            OnboardDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "40359@",
                            Phone = "8056064961",
                            StationId = "40359",
                            Status = true,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aadhaar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LoginAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aadhaar = "123456789012",
                            LoginAllowed = true,
                            Name = "Retinue",
                            Password = "Red@123",
                            Phone = "9943135008",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Aadhaar = "123456789013",
                            LoginAllowed = true,
                            Name = "Karthi",
                            Password = "Karthi123",
                            Phone = "9444488760",
                            Status = true
                        });
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.UserDistrict", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DistrictId");

                    b.HasIndex("DistrictId");

                    b.ToTable("UserDistrict");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DistrictId = 1
                        },
                        new
                        {
                            UserId = 1,
                            DistrictId = 2
                        },
                        new
                        {
                            UserId = 2,
                            DistrictId = 1
                        },
                        new
                        {
                            UserId = 2,
                            DistrictId = 2
                        });
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.Entrollment", b =>
                {
                    b.HasOne("CSCMasterAPI.Persistence.Entity.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSCMasterAPI.Persistence.Entity.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSCMasterAPI.Persistence.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.Member", b =>
                {
                    b.HasOne("CSCMasterAPI.Persistence.Entity.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSCMasterAPI.Persistence.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CSCMasterAPI.Persistence.Entity.UserDistrict", b =>
                {
                    b.HasOne("CSCMasterAPI.Persistence.Entity.District", null)
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CSCMasterAPI.Persistence.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
